### PR TITLE
Adding GraphQL endpoint

### PR DESCRIPTION
**Pull request by arthurdenner**
Hi, @afuh.

I was studying GraphQL today and to practise a little bit, I decided to add a GQL endpoint to this API. I believe that the result was pretty good, so I'm opening this PR to see if it interests you.

If it does, I believe we should see how to document the endpoint, even though with GQL the API is kind of self-documented. Also, it's my first time using GraphQL, so if you see any improvements that can be made, let me know.

Cheers. :smile:

### CODE REVIEW

**Comment by afuh** [comment]
Hey @arthurdenner, 
looks amazing, thank you so much for the awesome work!

It would be great if you could make a stand alone GraphQL library/wrapper with this instead of adding it to the main project. 

I’m going to add a couple of libraries to the documentation this week: there is a Ruby gem already and a Node client planned. It would be super nice if you want to contribute with your GQL wrapper.

**Comment by arthurdenner** [comment]
Thanks for the feedback, I'm glad you liked the idea! :smiley: 

I thought about creating a wrapper, even created [a branch](https://github.com/arthurdenner/rick-and-morty-api/tree/creating-graphql-wrapper) doing so, but I didn't like the result. Since the base API returns  URLs for things like the characters in an episode, the performance was not that good, because an episode can contain dozens of characters, what leads to dozens of requests and the response was kind of slow depending on the episode requested ([reference](https://github.com/arthurdenner/rick-and-morty-api/blob/creating-graphql-wrapper/graphql/resolvers.js#L57)).

But I'll take a better look to see how to improve the queries/requests with the filters and everything, because I didn't get to this point on the creating-graphql-wrapper branch. :+1:

**Comment by arthurdenner** [comment]
Hey @afuh, I created a GQL wrapper for the API ([see here](https://github.com/arthurdenner)). You can test it [here](https://rickandmortyapi-gql-gwkrokyifc.now.sh/).

I still have to improve the error handling and maybe add some more arguments for the queries, but I think it's pretty okay for now. Could you test it and give me some feedback?

Also, are you planning to add cache to this REST API?

**Comment by afuh** [comment]
Hey @arthurdenner, 
It's great, I really like it! It works like a charm
Just out of curiosity, can I ask why did you limit the depth to 3?

I just added cache to the server, give it a try and tell me what you think.  
If I find the time this week I will add the libraries/wrappers to the docs, is it ok if I add your GQL wrapper? 

Awesome work!

**Comment by arthurdenner** [comment]
To avoid malicious queries. Since the relations are recursive, one could make a query like this:

```
query charactersRecursive {
  characters {
    results {
      name
      episodes {
        name
        characters {
          name
          episodes {
            name
            // and on and on...
          }
        }
      }
    }
  }
}
```

With depth limit of 3, the max one can get is:

```
query charactersRecursive {
  characters {
    results {
      name
      episodes {
        name
      }
    }
  }
}
```

I can change the depth limit to 4, but I don't think that allowing for characters -> episodes -> characters (or any other structure like this) it's necessary.

And yeah, feel free to add the wrapper to the docs. :smile_cat:

**Comment by arthurdenner** [comment]
Closing this in favor of the [GraphQL wrapper](https://github.com/arthurdenner/rick-and-morty-graphql-api).

**Pull request closed without merging**
