### PR TITLE
Add docker build and docker-compose

### PR DESCRIPTION
**Pull request by EternalDeiwos**
I ran into your rate limiting while using this API and figured I could use a local deployment of the API so that I can reset it if I need to.

Let me know if this is something you'd be interested in and I can neaten it up a bit more.

### CODE REVIEW

**Comment by afuh** [comment]
Hey @EternalDeiwos 
it looks super handy, I will check it out asap. 
thanks!!

Just out of curiosity, do you hit the rate limit frequently?

**Comment by EternalDeiwos** [comment]
I'm may have pointed a class of students at it while teaching them about RESTful APIs. :sweat_smile:

We're all NATing behind a single address so we reach the limit pretty quickly.

**Comment by afuh** [comment]
I'm setting the headers in Nginx not in the API server. It should not be any issue with CORS. 

What kind of problems are you referring to? is it related to the Docker integration that you are proposing in this PR?

**Comment by EternalDeiwos** [comment]
Ah that would explain it. 

I'm not using any kind of reverse proxy so that's why I get the CORS error. Just deploying locally using docker for development purposes.

Technically this could also be addressed by adding a nginx container to the `docker-compose.yml` but that seems like overkill for a single header (for my purpose at least).

**Comment by afuh** [comment]
Since there is no more rate limit I will close this one. Thank you!

**Pull request closed without merging**
